site_name: NetAutLabs
site_description: Open-Source Network Automation Labs
site_url: https://netautlabs.net

nav:
  - Home: "index.md"
  - "Configuration Management":
    - "Ansible":
      - ansible-collect-configs/README.md
  - "Python":
    - python/comming_soon.md
  - "GoLang":
    - golang/comming_soon.md
  - "Testing and CI/CD":
    - testing/comming_soon.md
  - "Network Resource Managers":
    - resource_managers/comming_soon.md
  - "Foundational Skills":
    - foundation

repo_url: https://github.com/NetAutLabs/netautlabs
repo_name: NetAutLabs/netautlabs

theme:
  name: material
  palette:
    scheme: slate
    primary: purple
  language: en
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.code.select
  favicon: assets/logo.png
  logo: assets/logo_transparent_head.png

plugins:
  - search
  - social
  - tags
  - include_dir_to_nav
  - multirepo:
      cleanup: true
      keep_docs_dir: true
      nav_repos:
        - name: ansible-collect-configs
          import_url: "https://github.com/NetAutLabs/ansible_collect_configs?branch=main&edit_uri=/blob/main/'"
        

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences