site_name: NetAutLabs
site_description: Open-Source Network Automation Labs
site_url: https://netautlabs.net

nav:
  - Home: "index.md"
  - "Configuration Management":
    - "Ansible":
      - ansible-collect-configs/README.md
    - "StackStorm":
      - st2-webhook/README.md
  - "Python":
    - "PyTest":
      - python-pytest-device-helper/README.md
    - "Nornir":
      - nornir-mpls-l3-vpn-servic/README.md
  - "GoLang":
    - golang/comming_soon.md
  - "Testing and CI/CD":
    - testing/comming_soon.md
  - "Network Resource Managers":
    - resource_managers/comming_soon.md
  - "Foundational Skills":
    - foundation
  - Tags: tags.md

repo_url: https://github.com/NetAutLabs/netautlabs
repo_name: NetAutLabs/netautlabs

theme:
  name: material
  palette:
    scheme: slate
    primary: purple
  language: en
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.code.select
  favicon: assets/logo.png
  logo: assets/logo_transparent_head.png

plugins:
  - search
  - social
  - tags:
      tags_file: tags.md
  - include_dir_to_nav
  - multirepo:
      cleanup: true
      keep_docs_dir: true
      nav_repos:
        - name: ansible-collect-configs
          import_url: "https://github.com/NetAutLabs/ansible_collect_configs?branch=main&edit_uri=/blob/main/'"
        - name: python-pytest-device-helper
          import_url: "https://github.com/NetAutLabs/python_pytest_device_helper?branch=main&edit_uri=/blob/main/'"
        - name: nornir-mpls-l3-vpn-servic
          import_url: "https://github.com/NetAutLabs/nornir_mpls_l3_vpn_service?branch=main&edit_uri=/blob/main/'"
        - name: st2-webhook
          import_url: "https://github.com/NetAutLabs/st2_webhook?branch=main&edit_uri=/blob/main/'"
          imports: [
            imgs/*.png,
            /README.md,
            ]
        

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format